# Generated by Django 3.2.7 on 2022-09-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='un_checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('photo', models.ImageField(upload_to='un_checked')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.school')),
            ],
        ),
        migrations.CreateModel(
            name='checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('photo', models.ImageField(upload_to='checked')),
                ('un_checked_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.un_checked')),
            ],
        ),
    ]
